In [21]:
import pandas as pd
import requests

## Doc

The download function is only here if you don't alrealdy have the data files. To use it, had your github token in the var `token` and uncomment it.

To use this notebook, you don't need to download each data files each times. Comment the call to the download function when not need.

In [28]:
def dl_feather(f_path, f_name):
    file = f_name
    f_path += file
    
    # define parameters for a request
    #token = '' 
    owner = 'Travis-S-IBM'
    repo = 'q-kernel-ops'

    # send a request
    r = requests.get(
        'https://api.github.com/repos/{owner}/{repo}/contents/{path}'.format(
        owner=owner, repo=repo, path=f_path),
        headers={
            'accept': 'application/vnd.github.v3.raw',
            'authorization': 'token {}'.format(token)
                }
        )
    
    open("../" + f_path, 'wb').write(r.content)

## Telemetry

In [29]:
dl_feather("resources/kernel_metadata/", "telemetry_info.csv")

In [30]:
pd.read_feather("../resources/kernel_metadata/telemetry_info.csv")

,width,layers,circuit_id,job_id,time_queue,time_simu,payload_size
0,4,1,[10],c9dfep1c9c012ot5va60,7.563394,4.347188,88
1,4,1,[10],c9dff608vui0uejpbdog,7.263012,4.544997,88
2,4,1,[2],c9dficg8vui0uejpbt60,8.530053,4.651444,88
3,4,1,[5],c9dfj788vui0uejpbubg,7.168260,4.044550,88
4,4,1,[18],c9dfsro8vui0uejpdgog,7.610246,25.265974,2872
5,4,1,[2],c9dfugio1ctlqu0m8qhg,34.547719,245.638801,41880
6,4,1,[10],c9dg1r9c9c012ot61mn0,11.091617,62.073130,11288

## Kernel

In [34]:
k_name = "kernels-2-ideal.csv"
k_simu = "ibmq_qasm_simulator/"
dl_feather("resources/kernel_metadata/" + k_simu, k_name)

In [35]:
print(k_name)
print(k_simu)
pd.read_feather("../resources/kernel_metadata/" + k_simu + k_name)

kernels-2-ideal.csv
ibmq_qasm_simulator/

      width  layers  shots  seed_x  seed_y  fidelity
0         4       1   1024       0       0  1.000000
1         4       1   1024       1       0  0.854492
2         4       1   1024       1       1  1.000000
3         4       1   1024       2       0  0.851562
4         4       1   1024       2       1  0.815430
...     ...     ...    ...     ...     ...       ...
5146      4       1   1024     100      96  0.794922
5147      4       1   1024     100      97  0.717773
5148      4       1   1024     100      98  0.928711
5149      4       1   1024     100      99  0.757812
5150      4       1   1024     100     100  1.000000

[5151 rows x 6 columns]